# Generated by Django 4.2.4 on 2023-08-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_app', '0002_contact_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
