# Generated by Django 4.2.4 on 2023-08-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_app', '0003_remove_contact_created_at_remove_contact_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
