# Generated by Django 4.2.4 on 2023-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_app', '0004_apple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apple',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
